### ISSUE TITLE
Interested in Helping with Another Collection?

### ISSUE THREAD

**Issue by jrg94** [josephwegner/ineverylang#6]
Hey! I just stumbled upon this collection, and I noticed it hasn't been maintained in awhile. Would you be interested in transferring some of this work to an active repo? I'm currently building up a very similar collection called [Sample Programs](https://github.com/jrg94/sample-programs), and it's up over 80 languages now with over 100 snippets total.

There are several scripts that the Sample Programs collection doesn't support that you have in your collection such as binary search, fibonacci, nasa countdown, and tea party.

If that sounds interesting, let me know! 😃

**Comment by josephwegner** [comment]
Hey there @jrg94!

I don't have a ton of availability to move the content over to Sample Programs, but if you have the time you are more than welcome to reuse the content here. My only request would be that you propagate over and respect the [source for each solution](https://github.com/josephwegner/ineverylang/blob/master/source/puzzles/hello-world/go.txt#L2). This content is largely crowd-sourced, and the original authors deserve credit.

**Comment by jrg94** [comment]
Agreed! I wouldn't want to steal anyone's work. 

I'll probably start an issue over on my end and see if anyone can help me out.
